// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: mumax.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NULL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NULL) Reset() {
	*x = NULL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NULL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NULL) ProtoMessage() {}

func (x *NULL) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NULL.ProtoReflect.Descriptor instead.
func (*NULL) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{0}
}

type STRING struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *STRING) Reset() {
	*x = STRING{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *STRING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STRING) ProtoMessage() {}

func (x *STRING) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STRING.ProtoReflect.Descriptor instead.
func (*STRING) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{1}
}

func (x *STRING) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type STRINGs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S []string `protobuf:"bytes,1,rep,name=s,proto3" json:"s,omitempty"`
}

func (x *STRINGs) Reset() {
	*x = STRINGs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *STRINGs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STRINGs) ProtoMessage() {}

func (x *STRINGs) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STRINGs.ProtoReflect.Descriptor instead.
func (*STRINGs) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{2}
}

func (x *STRINGs) GetS() []string {
	if x != nil {
		return x.S
	}
	return nil
}

type BOOL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S bool `protobuf:"varint,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *BOOL) Reset() {
	*x = BOOL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BOOL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BOOL) ProtoMessage() {}

func (x *BOOL) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BOOL.ProtoReflect.Descriptor instead.
func (*BOOL) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{3}
}

func (x *BOOL) GetS() bool {
	if x != nil {
		return x.S
	}
	return false
}

type BOOLs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S []bool `protobuf:"varint,1,rep,packed,name=s,proto3" json:"s,omitempty"`
}

func (x *BOOLs) Reset() {
	*x = BOOLs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BOOLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BOOLs) ProtoMessage() {}

func (x *BOOLs) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BOOLs.ProtoReflect.Descriptor instead.
func (*BOOLs) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{4}
}

func (x *BOOLs) GetS() []bool {
	if x != nil {
		return x.S
	}
	return nil
}

type INT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S int64 `protobuf:"varint,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *INT) Reset() {
	*x = INT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INT) ProtoMessage() {}

func (x *INT) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INT.ProtoReflect.Descriptor instead.
func (*INT) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{5}
}

func (x *INT) GetS() int64 {
	if x != nil {
		return x.S
	}
	return 0
}

type INTs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S []int64 `protobuf:"varint,1,rep,packed,name=s,proto3" json:"s,omitempty"`
}

func (x *INTs) Reset() {
	*x = INTs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INTs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INTs) ProtoMessage() {}

func (x *INTs) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INTs.ProtoReflect.Descriptor instead.
func (*INTs) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{6}
}

func (x *INTs) GetS() []int64 {
	if x != nil {
		return x.S
	}
	return nil
}

type DOUBLE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S float64 `protobuf:"fixed64,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *DOUBLE) Reset() {
	*x = DOUBLE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DOUBLE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DOUBLE) ProtoMessage() {}

func (x *DOUBLE) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DOUBLE.ProtoReflect.Descriptor instead.
func (*DOUBLE) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{7}
}

func (x *DOUBLE) GetS() float64 {
	if x != nil {
		return x.S
	}
	return 0
}

type DOUBLEs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S []float64 `protobuf:"fixed64,1,rep,packed,name=s,proto3" json:"s,omitempty"`
}

func (x *DOUBLEs) Reset() {
	*x = DOUBLEs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DOUBLEs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DOUBLEs) ProtoMessage() {}

func (x *DOUBLEs) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DOUBLEs.ProtoReflect.Descriptor instead.
func (*DOUBLEs) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{8}
}

func (x *DOUBLEs) GetS() []float64 {
	if x != nil {
		return x.S
	}
	return nil
}

type Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Argtypes []string `protobuf:"bytes,1,rep,name=argtypes,proto3" json:"argtypes,omitempty"`
	Argnames []string `protobuf:"bytes,2,rep,name=argnames,proto3" json:"argnames,omitempty"`
	Outtypes []string `protobuf:"bytes,3,rep,name=outtypes,proto3" json:"outtypes,omitempty"`
}

func (x *Function) Reset() {
	*x = Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{9}
}

func (x *Function) GetArgtypes() []string {
	if x != nil {
		return x.Argtypes
	}
	return nil
}

func (x *Function) GetArgnames() []string {
	if x != nil {
		return x.Argnames
	}
	return nil
}

func (x *Function) GetOuttypes() []string {
	if x != nil {
		return x.Outtypes
	}
	return nil
}

type LValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Inputtype string `protobuf:"bytes,2,opt,name=inputtype,proto3" json:"inputtype,omitempty"`
}

func (x *LValue) Reset() {
	*x = LValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LValue) ProtoMessage() {}

func (x *LValue) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LValue.ProtoReflect.Descriptor instead.
func (*LValue) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{10}
}

func (x *LValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LValue) GetInputtype() string {
	if x != nil {
		return x.Inputtype
	}
	return ""
}

type ROnly struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ROnly) Reset() {
	*x = ROnly{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ROnly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ROnly) ProtoMessage() {}

func (x *ROnly) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ROnly.ProtoReflect.Descriptor instead.
func (*ROnly) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{11}
}

func (x *ROnly) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Identifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Doc  string `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	// Types that are assignable to Props:
	//
	//	*Identifier_L
	//	*Identifier_R
	//	*Identifier_F
	Props isIdentifier_Props `protobuf_oneof:"props"`
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{12}
}

func (x *Identifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identifier) GetDoc() string {
	if x != nil {
		return x.Doc
	}
	return ""
}

func (m *Identifier) GetProps() isIdentifier_Props {
	if m != nil {
		return m.Props
	}
	return nil
}

func (x *Identifier) GetL() *LValue {
	if x, ok := x.GetProps().(*Identifier_L); ok {
		return x.L
	}
	return nil
}

func (x *Identifier) GetR() *ROnly {
	if x, ok := x.GetProps().(*Identifier_R); ok {
		return x.R
	}
	return nil
}

func (x *Identifier) GetF() *Function {
	if x, ok := x.GetProps().(*Identifier_F); ok {
		return x.F
	}
	return nil
}

type isIdentifier_Props interface {
	isIdentifier_Props()
}

type Identifier_L struct {
	L *LValue `protobuf:"bytes,3,opt,name=l,proto3,oneof"`
}

type Identifier_R struct {
	R *ROnly `protobuf:"bytes,4,opt,name=r,proto3,oneof"`
}

type Identifier_F struct {
	F *Function `protobuf:"bytes,5,opt,name=f,proto3,oneof"`
}

func (*Identifier_L) isIdentifier_Props() {}

func (*Identifier_R) isIdentifier_Props() {}

func (*Identifier_F) isIdentifier_Props() {}

type MumaxObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Identity:
	//
	//	*MumaxObject_Name
	//	*MumaxObject_Ptr
	Identity isMumaxObject_Identity `protobuf_oneof:"identity"`
}

func (x *MumaxObject) Reset() {
	*x = MumaxObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MumaxObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MumaxObject) ProtoMessage() {}

func (x *MumaxObject) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MumaxObject.ProtoReflect.Descriptor instead.
func (*MumaxObject) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{13}
}

func (m *MumaxObject) GetIdentity() isMumaxObject_Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (x *MumaxObject) GetName() string {
	if x, ok := x.GetIdentity().(*MumaxObject_Name); ok {
		return x.Name
	}
	return ""
}

func (x *MumaxObject) GetPtr() uint32 {
	if x, ok := x.GetIdentity().(*MumaxObject_Ptr); ok {
		return x.Ptr
	}
	return 0
}

type isMumaxObject_Identity interface {
	isMumaxObject_Identity()
}

type MumaxObject_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type MumaxObject_Ptr struct {
	Ptr uint32 `protobuf:"varint,2,opt,name=ptr,proto3,oneof"`
}

func (*MumaxObject_Name) isMumaxObject_Identity() {}

func (*MumaxObject_Ptr) isMumaxObject_Identity() {}

type MumaxObjects struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S []*MumaxObject `protobuf:"bytes,1,rep,name=s,proto3" json:"s,omitempty"`
}

func (x *MumaxObjects) Reset() {
	*x = MumaxObjects{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MumaxObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MumaxObjects) ProtoMessage() {}

func (x *MumaxObjects) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MumaxObjects.ProtoReflect.Descriptor instead.
func (*MumaxObjects) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{14}
}

func (x *MumaxObjects) GetS() []*MumaxObject {
	if x != nil {
		return x.S
	}
	return nil
}

type FunctionCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ArgString         []string          `protobuf:"bytes,2,rep,name=argString,proto3" json:"argString,omitempty"`
	ArgBool           []bool            `protobuf:"varint,3,rep,packed,name=argBool,proto3" json:"argBool,omitempty"`
	ArgDouble         []float64         `protobuf:"fixed64,4,rep,packed,name=argDouble,proto3" json:"argDouble,omitempty"`
	ArgInt            []int64           `protobuf:"varint,5,rep,packed,name=argInt,proto3" json:"argInt,omitempty"`
	ArgMumax          []*MumaxObject    `protobuf:"bytes,6,rep,name=argMumax,proto3" json:"argMumax,omitempty"`
	ArgScalarFunction []*ScalarFunction `protobuf:"bytes,7,rep,name=argScalarFunction,proto3" json:"argScalarFunction,omitempty"`
	ArgVectorFunction []*VectorFunction `protobuf:"bytes,8,rep,name=argVectorFunction,proto3" json:"argVectorFunction,omitempty"`
}

func (x *FunctionCall) Reset() {
	*x = FunctionCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionCall) ProtoMessage() {}

func (x *FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionCall.ProtoReflect.Descriptor instead.
func (*FunctionCall) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{15}
}

func (x *FunctionCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionCall) GetArgString() []string {
	if x != nil {
		return x.ArgString
	}
	return nil
}

func (x *FunctionCall) GetArgBool() []bool {
	if x != nil {
		return x.ArgBool
	}
	return nil
}

func (x *FunctionCall) GetArgDouble() []float64 {
	if x != nil {
		return x.ArgDouble
	}
	return nil
}

func (x *FunctionCall) GetArgInt() []int64 {
	if x != nil {
		return x.ArgInt
	}
	return nil
}

func (x *FunctionCall) GetArgMumax() []*MumaxObject {
	if x != nil {
		return x.ArgMumax
	}
	return nil
}

func (x *FunctionCall) GetArgScalarFunction() []*ScalarFunction {
	if x != nil {
		return x.ArgScalarFunction
	}
	return nil
}

func (x *FunctionCall) GetArgVectorFunction() []*VectorFunction {
	if x != nil {
		return x.ArgVectorFunction
	}
	return nil
}

type Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Elements:
	//
	//	*Array_I
	//	*Array_B
	//	*Array_S
	//	*Array_D
	//	*Array_O
	//	*Array_A
	Elements isArray_Elements `protobuf_oneof:"elements"`
}

func (x *Array) Reset() {
	*x = Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array) ProtoMessage() {}

func (x *Array) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array.ProtoReflect.Descriptor instead.
func (*Array) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{16}
}

func (m *Array) GetElements() isArray_Elements {
	if m != nil {
		return m.Elements
	}
	return nil
}

func (x *Array) GetI() *INTs {
	if x, ok := x.GetElements().(*Array_I); ok {
		return x.I
	}
	return nil
}

func (x *Array) GetB() *BOOLs {
	if x, ok := x.GetElements().(*Array_B); ok {
		return x.B
	}
	return nil
}

func (x *Array) GetS() *STRINGs {
	if x, ok := x.GetElements().(*Array_S); ok {
		return x.S
	}
	return nil
}

func (x *Array) GetD() *DOUBLEs {
	if x, ok := x.GetElements().(*Array_D); ok {
		return x.D
	}
	return nil
}

func (x *Array) GetO() *MumaxObjects {
	if x, ok := x.GetElements().(*Array_O); ok {
		return x.O
	}
	return nil
}

func (x *Array) GetA() *Arrays {
	if x, ok := x.GetElements().(*Array_A); ok {
		return x.A
	}
	return nil
}

type isArray_Elements interface {
	isArray_Elements()
}

type Array_I struct {
	I *INTs `protobuf:"bytes,1,opt,name=i,proto3,oneof"`
}

type Array_B struct {
	B *BOOLs `protobuf:"bytes,2,opt,name=b,proto3,oneof"`
}

type Array_S struct {
	S *STRINGs `protobuf:"bytes,3,opt,name=s,proto3,oneof"`
}

type Array_D struct {
	D *DOUBLEs `protobuf:"bytes,4,opt,name=d,proto3,oneof"`
}

type Array_O struct {
	O *MumaxObjects `protobuf:"bytes,5,opt,name=o,proto3,oneof"`
}

type Array_A struct {
	A *Arrays `protobuf:"bytes,6,opt,name=a,proto3,oneof"`
}

func (*Array_I) isArray_Elements() {}

func (*Array_B) isArray_Elements() {}

func (*Array_S) isArray_Elements() {}

func (*Array_D) isArray_Elements() {}

func (*Array_O) isArray_Elements() {}

func (*Array_A) isArray_Elements() {}

type Arrays struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S []*Array `protobuf:"bytes,1,rep,name=s,proto3" json:"s,omitempty"`
}

func (x *Arrays) Reset() {
	*x = Arrays{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Arrays) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arrays) ProtoMessage() {}

func (x *Arrays) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arrays.ProtoReflect.Descriptor instead.
func (*Arrays) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{17}
}

func (x *Arrays) GetS() []*Array {
	if x != nil {
		return x.S
	}
	return nil
}

type CallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutString []string       `protobuf:"bytes,2,rep,name=outString,proto3" json:"outString,omitempty"`
	OutBool   []bool         `protobuf:"varint,3,rep,packed,name=outBool,proto3" json:"outBool,omitempty"`
	OutDouble []float64      `protobuf:"fixed64,4,rep,packed,name=outDouble,proto3" json:"outDouble,omitempty"`
	OutInt    []int64        `protobuf:"varint,5,rep,packed,name=outInt,proto3" json:"outInt,omitempty"`
	OutMumax  []*MumaxObject `protobuf:"bytes,6,rep,name=outMumax,proto3" json:"outMumax,omitempty"`
	OutArray  []*Array       `protobuf:"bytes,7,rep,name=outArray,proto3" json:"outArray,omitempty"`
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{18}
}

func (x *CallResponse) GetOutString() []string {
	if x != nil {
		return x.OutString
	}
	return nil
}

func (x *CallResponse) GetOutBool() []bool {
	if x != nil {
		return x.OutBool
	}
	return nil
}

func (x *CallResponse) GetOutDouble() []float64 {
	if x != nil {
		return x.OutDouble
	}
	return nil
}

func (x *CallResponse) GetOutInt() []int64 {
	if x != nil {
		return x.OutInt
	}
	return nil
}

func (x *CallResponse) GetOutMumax() []*MumaxObject {
	if x != nil {
		return x.OutMumax
	}
	return nil
}

func (x *CallResponse) GetOutArray() []*Array {
	if x != nil {
		return x.OutArray
	}
	return nil
}

type MethodCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmobj *MumaxObject  `protobuf:"bytes,1,opt,name=mmobj,proto3" json:"mmobj,omitempty"`
	Fc    *FunctionCall `protobuf:"bytes,2,opt,name=fc,proto3" json:"fc,omitempty"`
}

func (x *MethodCall) Reset() {
	*x = MethodCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodCall) ProtoMessage() {}

func (x *MethodCall) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodCall.ProtoReflect.Descriptor instead.
func (*MethodCall) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{19}
}

func (x *MethodCall) GetMmobj() *MumaxObject {
	if x != nil {
		return x.Mmobj
	}
	return nil
}

func (x *MethodCall) GetFc() *FunctionCall {
	if x != nil {
		return x.Fc
	}
	return nil
}

type MumaxField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmobj     *MumaxObject `protobuf:"bytes,1,opt,name=mmobj,proto3" json:"mmobj,omitempty"`
	FieldName string       `protobuf:"bytes,2,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
}

func (x *MumaxField) Reset() {
	*x = MumaxField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MumaxField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MumaxField) ProtoMessage() {}

func (x *MumaxField) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MumaxField.ProtoReflect.Descriptor instead.
func (*MumaxField) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{20}
}

func (x *MumaxField) GetMmobj() *MumaxObject {
	if x != nil {
		return x.Mmobj
	}
	return nil
}

func (x *MumaxField) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

type BoolSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmobj *MumaxObject `protobuf:"bytes,1,opt,name=mmobj,proto3" json:"mmobj,omitempty"`
	S     bool         `protobuf:"varint,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *BoolSet) Reset() {
	*x = BoolSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolSet) ProtoMessage() {}

func (x *BoolSet) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolSet.ProtoReflect.Descriptor instead.
func (*BoolSet) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{21}
}

func (x *BoolSet) GetMmobj() *MumaxObject {
	if x != nil {
		return x.Mmobj
	}
	return nil
}

func (x *BoolSet) GetS() bool {
	if x != nil {
		return x.S
	}
	return false
}

type IntSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmobj *MumaxObject `protobuf:"bytes,1,opt,name=mmobj,proto3" json:"mmobj,omitempty"`
	S     int64        `protobuf:"varint,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *IntSet) Reset() {
	*x = IntSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntSet) ProtoMessage() {}

func (x *IntSet) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntSet.ProtoReflect.Descriptor instead.
func (*IntSet) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{22}
}

func (x *IntSet) GetMmobj() *MumaxObject {
	if x != nil {
		return x.Mmobj
	}
	return nil
}

func (x *IntSet) GetS() int64 {
	if x != nil {
		return x.S
	}
	return 0
}

type DoubleSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmobj *MumaxObject `protobuf:"bytes,1,opt,name=mmobj,proto3" json:"mmobj,omitempty"`
	S     float64      `protobuf:"fixed64,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *DoubleSet) Reset() {
	*x = DoubleSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleSet) ProtoMessage() {}

func (x *DoubleSet) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleSet.ProtoReflect.Descriptor instead.
func (*DoubleSet) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{23}
}

func (x *DoubleSet) GetMmobj() *MumaxObject {
	if x != nil {
		return x.Mmobj
	}
	return nil
}

func (x *DoubleSet) GetS() float64 {
	if x != nil {
		return x.S
	}
	return 0
}

type StringSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmobj *MumaxObject `protobuf:"bytes,1,opt,name=mmobj,proto3" json:"mmobj,omitempty"`
	S     string       `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *StringSet) Reset() {
	*x = StringSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringSet) ProtoMessage() {}

func (x *StringSet) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringSet.ProtoReflect.Descriptor instead.
func (*StringSet) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{24}
}

func (x *StringSet) GetMmobj() *MumaxObject {
	if x != nil {
		return x.Mmobj
	}
	return nil
}

func (x *StringSet) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type VectorSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmobj *MumaxObject `protobuf:"bytes,1,opt,name=mmobj,proto3" json:"mmobj,omitempty"`
	X     float64      `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y     float64      `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Z     float64      `protobuf:"fixed64,4,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *VectorSet) Reset() {
	*x = VectorSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSet) ProtoMessage() {}

func (x *VectorSet) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSet.ProtoReflect.Descriptor instead.
func (*VectorSet) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{25}
}

func (x *VectorSet) GetMmobj() *MumaxObject {
	if x != nil {
		return x.Mmobj
	}
	return nil
}

func (x *VectorSet) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *VectorSet) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *VectorSet) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type ScalarFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Sf:
	//
	//	*ScalarFunction_Scalar
	//	*ScalarFunction_Gocode
	Sf isScalarFunction_Sf `protobuf_oneof:"sf"`
}

func (x *ScalarFunction) Reset() {
	*x = ScalarFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScalarFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarFunction) ProtoMessage() {}

func (x *ScalarFunction) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarFunction.ProtoReflect.Descriptor instead.
func (*ScalarFunction) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{26}
}

func (m *ScalarFunction) GetSf() isScalarFunction_Sf {
	if m != nil {
		return m.Sf
	}
	return nil
}

func (x *ScalarFunction) GetScalar() float64 {
	if x, ok := x.GetSf().(*ScalarFunction_Scalar); ok {
		return x.Scalar
	}
	return 0
}

func (x *ScalarFunction) GetGocode() string {
	if x, ok := x.GetSf().(*ScalarFunction_Gocode); ok {
		return x.Gocode
	}
	return ""
}

type isScalarFunction_Sf interface {
	isScalarFunction_Sf()
}

type ScalarFunction_Scalar struct {
	Scalar float64 `protobuf:"fixed64,2,opt,name=scalar,proto3,oneof"`
}

type ScalarFunction_Gocode struct {
	Gocode string `protobuf:"bytes,3,opt,name=gocode,proto3,oneof"`
}

func (*ScalarFunction_Scalar) isScalarFunction_Sf() {}

func (*ScalarFunction_Gocode) isScalarFunction_Sf() {}

type ScalarFunctionSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmobj *MumaxObject    `protobuf:"bytes,1,opt,name=mmobj,proto3" json:"mmobj,omitempty"`
	S     *ScalarFunction `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *ScalarFunctionSet) Reset() {
	*x = ScalarFunctionSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScalarFunctionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarFunctionSet) ProtoMessage() {}

func (x *ScalarFunctionSet) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarFunctionSet.ProtoReflect.Descriptor instead.
func (*ScalarFunctionSet) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{27}
}

func (x *ScalarFunctionSet) GetMmobj() *MumaxObject {
	if x != nil {
		return x.Mmobj
	}
	return nil
}

func (x *ScalarFunctionSet) GetS() *ScalarFunction {
	if x != nil {
		return x.S
	}
	return nil
}

type ScalarFunction3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *ScalarFunction `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y *ScalarFunction `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	Z *ScalarFunction `protobuf:"bytes,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *ScalarFunction3) Reset() {
	*x = ScalarFunction3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScalarFunction3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalarFunction3) ProtoMessage() {}

func (x *ScalarFunction3) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalarFunction3.ProtoReflect.Descriptor instead.
func (*ScalarFunction3) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{28}
}

func (x *ScalarFunction3) GetX() *ScalarFunction {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *ScalarFunction3) GetY() *ScalarFunction {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *ScalarFunction3) GetZ() *ScalarFunction {
	if x != nil {
		return x.Z
	}
	return nil
}

type VectorFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Vf:
	//
	//	*VectorFunction_Gocode
	//	*VectorFunction_Components
	Vf isVectorFunction_Vf `protobuf_oneof:"vf"`
}

func (x *VectorFunction) Reset() {
	*x = VectorFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorFunction) ProtoMessage() {}

func (x *VectorFunction) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorFunction.ProtoReflect.Descriptor instead.
func (*VectorFunction) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{29}
}

func (m *VectorFunction) GetVf() isVectorFunction_Vf {
	if m != nil {
		return m.Vf
	}
	return nil
}

func (x *VectorFunction) GetGocode() string {
	if x, ok := x.GetVf().(*VectorFunction_Gocode); ok {
		return x.Gocode
	}
	return ""
}

func (x *VectorFunction) GetComponents() *ScalarFunction3 {
	if x, ok := x.GetVf().(*VectorFunction_Components); ok {
		return x.Components
	}
	return nil
}

type isVectorFunction_Vf interface {
	isVectorFunction_Vf()
}

type VectorFunction_Gocode struct {
	Gocode string `protobuf:"bytes,1,opt,name=gocode,proto3,oneof"`
}

type VectorFunction_Components struct {
	Components *ScalarFunction3 `protobuf:"bytes,2,opt,name=components,proto3,oneof"`
}

func (*VectorFunction_Gocode) isVectorFunction_Vf() {}

func (*VectorFunction_Components) isVectorFunction_Vf() {}

type VectorFunctionSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmobj *MumaxObject    `protobuf:"bytes,1,opt,name=mmobj,proto3" json:"mmobj,omitempty"`
	S     *VectorFunction `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *VectorFunctionSet) Reset() {
	*x = VectorFunctionSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VectorFunctionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorFunctionSet) ProtoMessage() {}

func (x *VectorFunctionSet) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorFunctionSet.ProtoReflect.Descriptor instead.
func (*VectorFunctionSet) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{30}
}

func (x *VectorFunctionSet) GetMmobj() *MumaxObject {
	if x != nil {
		return x.Mmobj
	}
	return nil
}

func (x *VectorFunctionSet) GetS() *VectorFunction {
	if x != nil {
		return x.S
	}
	return nil
}

type MumaxSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mmobj *MumaxObject `protobuf:"bytes,1,opt,name=mmobj,proto3" json:"mmobj,omitempty"`
	S     *MumaxObject `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *MumaxSet) Reset() {
	*x = MumaxSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MumaxSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MumaxSet) ProtoMessage() {}

func (x *MumaxSet) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MumaxSet.ProtoReflect.Descriptor instead.
func (*MumaxSet) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{31}
}

func (x *MumaxSet) GetMmobj() *MumaxObject {
	if x != nil {
		return x.Mmobj
	}
	return nil
}

func (x *MumaxSet) GetS() *MumaxObject {
	if x != nil {
		return x.S
	}
	return nil
}

type Slice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ncomp int64  `protobuf:"varint,1,opt,name=ncomp,proto3" json:"ncomp,omitempty"`
	Nx    int64  `protobuf:"varint,2,opt,name=nx,proto3" json:"nx,omitempty"`
	Ny    int64  `protobuf:"varint,3,opt,name=ny,proto3" json:"ny,omitempty"`
	Nz    int64  `protobuf:"varint,4,opt,name=nz,proto3" json:"nz,omitempty"`
	File  string `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *Slice) Reset() {
	*x = Slice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mumax_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slice) ProtoMessage() {}

func (x *Slice) ProtoReflect() protoreflect.Message {
	mi := &file_mumax_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slice.ProtoReflect.Descriptor instead.
func (*Slice) Descriptor() ([]byte, []int) {
	return file_mumax_proto_rawDescGZIP(), []int{32}
}

func (x *Slice) GetNcomp() int64 {
	if x != nil {
		return x.Ncomp
	}
	return 0
}

func (x *Slice) GetNx() int64 {
	if x != nil {
		return x.Nx
	}
	return 0
}

func (x *Slice) GetNy() int64 {
	if x != nil {
		return x.Ny
	}
	return 0
}

func (x *Slice) GetNz() int64 {
	if x != nil {
		return x.Nz
	}
	return 0
}

func (x *Slice) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

var File_mumax_proto protoreflect.FileDescriptor

var file_mumax_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d,
	0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x22, 0x06, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x22, 0x16,
	0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x17, 0x0a, 0x07, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47,
	0x73, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22,
	0x14, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x01, 0x73, 0x22, 0x15, 0x0a, 0x05, 0x42, 0x4f, 0x4f, 0x4c, 0x73, 0x12, 0x0c,
	0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x01, 0x73, 0x22, 0x13, 0x0a, 0x03,
	0x49, 0x4e, 0x54, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x73, 0x22, 0x14, 0x0a, 0x04, 0x49, 0x4e, 0x54, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x01, 0x73, 0x22, 0x16, 0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c,
	0x45, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x73, 0x22,
	0x17, 0x0a, 0x07, 0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x01, 0x73, 0x22, 0x5e, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x67, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x67, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x72, 0x67, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x67, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x6f, 0x75, 0x74, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x6f, 0x75, 0x74, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x06, 0x4c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x1b, 0x0a, 0x05, 0x52, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x9f, 0x01, 0x0a, 0x0a, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x64, 0x6f, 0x63, 0x12, 0x1f, 0x0a, 0x01, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x48, 0x00, 0x52, 0x01, 0x6c, 0x12, 0x1e, 0x0a, 0x01, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x52, 0x4f, 0x6e,
	0x6c, 0x79, 0x48, 0x00, 0x52, 0x01, 0x72, 0x12, 0x21, 0x0a, 0x01, 0x66, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x01, 0x66, 0x42, 0x07, 0x0a, 0x05, 0x70, 0x72,
	0x6f, 0x70, 0x73, 0x22, 0x43, 0x0a, 0x0b, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x03, 0x70, 0x74, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x03, 0x70, 0x74, 0x72, 0x42, 0x0a, 0x0a, 0x08,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x32, 0x0a, 0x0c, 0x4d, 0x75, 0x6d, 0x61,
	0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75,
	0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x01, 0x73, 0x22, 0xd0, 0x02, 0x0a,
	0x0c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x67, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x72, 0x67, 0x42, 0x6f, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x08,
	0x52, 0x07, 0x61, 0x72, 0x67, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x67,
	0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x61, 0x72,
	0x67, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x67, 0x49, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x61, 0x72, 0x67, 0x49, 0x6e, 0x74, 0x12,
	0x30, 0x0a, 0x08, 0x61, 0x72, 0x67, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61,
	0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x08, 0x61, 0x72, 0x67, 0x4d, 0x75, 0x6d, 0x61,
	0x78, 0x12, 0x45, 0x0a, 0x11, 0x61, 0x72, 0x67, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d,
	0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x61, 0x72, 0x67, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x45, 0x0a, 0x11, 0x61, 0x72, 0x67, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x61, 0x72,
	0x67, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0xde, 0x01, 0x0a, 0x05, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x1d, 0x0a, 0x01, 0x69, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x49,
	0x4e, 0x54, 0x73, 0x48, 0x00, 0x52, 0x01, 0x69, 0x12, 0x1e, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x42, 0x4f,
	0x4f, 0x4c, 0x73, 0x48, 0x00, 0x52, 0x01, 0x62, 0x12, 0x20, 0x0a, 0x01, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x53, 0x54,
	0x52, 0x49, 0x4e, 0x47, 0x73, 0x48, 0x00, 0x52, 0x01, 0x73, 0x12, 0x20, 0x0a, 0x01, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e,
	0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x73, 0x48, 0x00, 0x52, 0x01, 0x64, 0x12, 0x25, 0x0a, 0x01,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70,
	0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x48, 0x00,
	0x52, 0x01, 0x6f, 0x12, 0x1f, 0x0a, 0x01, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x73, 0x48,
	0x00, 0x52, 0x01, 0x61, 0x42, 0x0a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x26, 0x0a, 0x06, 0x41, 0x72, 0x72, 0x61, 0x79, 0x73, 0x12, 0x1c, 0x0a, 0x01, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x01, 0x73, 0x22, 0xda, 0x01, 0x0a, 0x0c, 0x43, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x75,
	0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x42, 0x6f,
	0x6f, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x08, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x42, 0x6f, 0x6f,
	0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x49, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x06, 0x6f, 0x75, 0x74, 0x49, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x4d, 0x75,
	0x6d, 0x61, 0x78, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61,
	0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x08, 0x6f, 0x75, 0x74, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x12, 0x2a, 0x0a, 0x08, 0x6f, 0x75, 0x74,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x75,
	0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x08, 0x6f, 0x75, 0x74,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x22, 0x5f, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x43,
	0x61, 0x6c, 0x6c, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d,
	0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x12,
	0x25, 0x0a, 0x02, 0x66, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x75,
	0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61,
	0x6c, 0x6c, 0x52, 0x02, 0x66, 0x63, 0x22, 0x56, 0x0a, 0x0a, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75,
	0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x43,
	0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6c, 0x53, 0x65, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6d, 0x6f,
	0x62, 0x6a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78,
	0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05,
	0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x01, 0x73, 0x22, 0x42, 0x0a, 0x06, 0x49, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x12, 0x2a, 0x0a,
	0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d,
	0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x73, 0x22, 0x45, 0x0a, 0x09, 0x44, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x53, 0x65, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75,
	0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a,
	0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x73, 0x22, 0x45,
	0x0a, 0x09, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x6d,
	0x6d, 0x6f, 0x62, 0x6a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d,
	0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0x61, 0x0a, 0x09, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53,
	0x65, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61,
	0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x7a, 0x22, 0x4a, 0x0a, 0x0e, 0x53, 0x63, 0x61, 0x6c,
	0x61, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x63,
	0x61, 0x6c, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x73, 0x63,
	0x61, 0x6c, 0x61, 0x72, 0x12, 0x18, 0x0a, 0x06, 0x67, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x67, 0x6f, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x04,
	0x0a, 0x02, 0x73, 0x66, 0x22, 0x66, 0x0a, 0x11, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6d, 0x6f,
	0x62, 0x6a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78,
	0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05,
	0x6d, 0x6d, 0x6f, 0x62, 0x6a, 0x12, 0x25, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61,
	0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x01, 0x73, 0x22, 0x86, 0x01, 0x0a,
	0x0f, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x33,
	0x12, 0x25, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x75,
	0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x01, 0x78, 0x12, 0x25, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x53, 0x63, 0x61,
	0x6c, 0x61, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x01, 0x79, 0x12, 0x25,
	0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x75, 0x6d, 0x61,
	0x78, 0x70, 0x79, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x01, 0x7a, 0x22, 0x6c, 0x0a, 0x0e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x06, 0x67, 0x6f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x67, 0x6f, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e,
	0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x33, 0x48,
	0x00, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x04, 0x0a,
	0x02, 0x76, 0x66, 0x22, 0x66, 0x0a, 0x11, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6d, 0x6f, 0x62,
	0x6a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70,
	0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05, 0x6d,
	0x6d, 0x6f, 0x62, 0x6a, 0x12, 0x25, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x01, 0x73, 0x22, 0x5a, 0x0a, 0x08, 0x4d,
	0x75, 0x6d, 0x61, 0x78, 0x53, 0x65, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6d, 0x6f, 0x62, 0x6a,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79,
	0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05, 0x6d, 0x6d,
	0x6f, 0x62, 0x6a, 0x12, 0x22, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x01, 0x73, 0x22, 0x61, 0x0a, 0x05, 0x53, 0x6c, 0x69, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6e, 0x63, 0x6f, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6e, 0x63, 0x6f, 0x6d, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x6e, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x6e, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x7a, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x6e, 0x7a, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x32, 0x91, 0x0a, 0x0a, 0x05, 0x6d,
	0x75, 0x6d, 0x61, 0x78, 0x12, 0x28, 0x0a, 0x04, 0x45, 0x76, 0x61, 0x6c, 0x12, 0x0f, 0x2e, 0x6d,
	0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x1a, 0x0d, 0x2e,
	0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4e, 0x55, 0x4c, 0x4c, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x73,
	0x12, 0x0d, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4e, 0x55, 0x4c, 0x4c, 0x1a,
	0x13, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x22, 0x00, 0x30, 0x01, 0x12, 0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70,
	0x79, 0x2e, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x1a, 0x13, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78,
	0x70, 0x79, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x36, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x15, 0x2e, 0x6d, 0x75, 0x6d, 0x61,
	0x78, 0x70, 0x79, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c,
	0x1a, 0x15, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x43, 0x61, 0x6c,
	0x6c, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x13, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70,
	0x79, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x1a, 0x15, 0x2e, 0x6d,
	0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6c,
	0x12, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x0d, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79,
	0x2e, 0x42, 0x4f, 0x4f, 0x4c, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x49, 0x6e,
	0x74, 0x12, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61,
	0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x0c, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70,
	0x79, 0x2e, 0x49, 0x4e, 0x54, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d,
	0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x0f, 0x2e, 0x6d, 0x75, 0x6d,
	0x61, 0x78, 0x70, 0x79, 0x2e, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x22, 0x00, 0x12, 0x34, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x2e, 0x6d, 0x75, 0x6d,
	0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x1a, 0x0f, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x44, 0x4f, 0x55, 0x42, 0x4c,
	0x45, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x10,
	0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x53, 0x65, 0x74,
	0x1a, 0x0d, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4e, 0x55, 0x4c, 0x4c, 0x22,
	0x00, 0x12, 0x2a, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x6d, 0x75,
	0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x49, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x1a, 0x0d, 0x2e, 0x6d,
	0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4e, 0x55, 0x4c, 0x4c, 0x22, 0x00, 0x12, 0x30, 0x0a,
	0x09, 0x53, 0x65, 0x74, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x6d, 0x75, 0x6d,
	0x61, 0x78, 0x70, 0x79, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x1a, 0x0d,
	0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4e, 0x55, 0x4c, 0x4c, 0x22, 0x00, 0x12,
	0x30, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x2e, 0x6d,
	0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x74,
	0x1a, 0x0d, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4e, 0x55, 0x4c, 0x4c, 0x22,
	0x00, 0x12, 0x30, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12,
	0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x53,
	0x65, 0x74, 0x1a, 0x0d, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4e, 0x55, 0x4c,
	0x4c, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78,
	0x70, 0x79, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x74, 0x1a, 0x0d, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4e,
	0x55, 0x4c, 0x4c, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x6d, 0x75, 0x6d,
	0x61, 0x78, 0x70, 0x79, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x1a, 0x0d, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79,
	0x2e, 0x4e, 0x55, 0x4c, 0x4c, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x4d, 0x75,
	0x6d, 0x61, 0x78, 0x12, 0x11, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75,
	0x6d, 0x61, 0x78, 0x53, 0x65, 0x74, 0x1a, 0x0d, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79,
	0x2e, 0x4e, 0x55, 0x4c, 0x4c, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x13, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70,
	0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x0d, 0x2e, 0x6d,
	0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x42, 0x4f, 0x4f, 0x4c, 0x22, 0x00, 0x12, 0x32, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x6e, 0x74, 0x12, 0x13, 0x2e, 0x6d,
	0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x1a, 0x0c, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x49, 0x4e, 0x54, 0x22,
	0x00, 0x12, 0x38, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x13, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75,
	0x6d, 0x61, 0x78, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x0f, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78,
	0x70, 0x79, 0x2e, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x13, 0x2e,
	0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x1a, 0x0f, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x44, 0x4f, 0x55,
	0x42, 0x4c, 0x45, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x12, 0x13, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79,
	0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x1a, 0x14, 0x2e, 0x6d, 0x75,
	0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x4d, 0x75,
	0x6d, 0x61, 0x78, 0x12, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79, 0x2e, 0x4d, 0x75,
	0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x0d, 0x2e, 0x6d, 0x75, 0x6d, 0x61,
	0x78, 0x70, 0x79, 0x2e, 0x4e, 0x55, 0x4c, 0x4c, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x4e, 0x65,
	0x77, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79,
	0x2e, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x1a, 0x14, 0x2e, 0x6d, 0x75, 0x6d, 0x61, 0x78, 0x70, 0x79,
	0x2e, 0x4d, 0x75, 0x6d, 0x61, 0x78, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x00, 0x42, 0x2c,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x69, 0x6c,
	0x6c, 0x2d, 0x68, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2f, 0x6d, 0x75, 0x6d, 0x61,
	0x78, 0x70, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mumax_proto_rawDescOnce sync.Once
	file_mumax_proto_rawDescData = file_mumax_proto_rawDesc
)

func file_mumax_proto_rawDescGZIP() []byte {
	file_mumax_proto_rawDescOnce.Do(func() {
		file_mumax_proto_rawDescData = protoimpl.X.CompressGZIP(file_mumax_proto_rawDescData)
	})
	return file_mumax_proto_rawDescData
}

var file_mumax_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_mumax_proto_goTypes = []interface{}{
	(*NULL)(nil),              // 0: mumaxpy.NULL
	(*STRING)(nil),            // 1: mumaxpy.STRING
	(*STRINGs)(nil),           // 2: mumaxpy.STRINGs
	(*BOOL)(nil),              // 3: mumaxpy.BOOL
	(*BOOLs)(nil),             // 4: mumaxpy.BOOLs
	(*INT)(nil),               // 5: mumaxpy.INT
	(*INTs)(nil),              // 6: mumaxpy.INTs
	(*DOUBLE)(nil),            // 7: mumaxpy.DOUBLE
	(*DOUBLEs)(nil),           // 8: mumaxpy.DOUBLEs
	(*Function)(nil),          // 9: mumaxpy.Function
	(*LValue)(nil),            // 10: mumaxpy.LValue
	(*ROnly)(nil),             // 11: mumaxpy.ROnly
	(*Identifier)(nil),        // 12: mumaxpy.Identifier
	(*MumaxObject)(nil),       // 13: mumaxpy.MumaxObject
	(*MumaxObjects)(nil),      // 14: mumaxpy.MumaxObjects
	(*FunctionCall)(nil),      // 15: mumaxpy.FunctionCall
	(*Array)(nil),             // 16: mumaxpy.Array
	(*Arrays)(nil),            // 17: mumaxpy.Arrays
	(*CallResponse)(nil),      // 18: mumaxpy.CallResponse
	(*MethodCall)(nil),        // 19: mumaxpy.MethodCall
	(*MumaxField)(nil),        // 20: mumaxpy.MumaxField
	(*BoolSet)(nil),           // 21: mumaxpy.BoolSet
	(*IntSet)(nil),            // 22: mumaxpy.IntSet
	(*DoubleSet)(nil),         // 23: mumaxpy.DoubleSet
	(*StringSet)(nil),         // 24: mumaxpy.StringSet
	(*VectorSet)(nil),         // 25: mumaxpy.VectorSet
	(*ScalarFunction)(nil),    // 26: mumaxpy.ScalarFunction
	(*ScalarFunctionSet)(nil), // 27: mumaxpy.ScalarFunctionSet
	(*ScalarFunction3)(nil),   // 28: mumaxpy.ScalarFunction3
	(*VectorFunction)(nil),    // 29: mumaxpy.VectorFunction
	(*VectorFunctionSet)(nil), // 30: mumaxpy.VectorFunctionSet
	(*MumaxSet)(nil),          // 31: mumaxpy.MumaxSet
	(*Slice)(nil),             // 32: mumaxpy.Slice
}
var file_mumax_proto_depIdxs = []int32{
	10, // 0: mumaxpy.Identifier.l:type_name -> mumaxpy.LValue
	11, // 1: mumaxpy.Identifier.r:type_name -> mumaxpy.ROnly
	9,  // 2: mumaxpy.Identifier.f:type_name -> mumaxpy.Function
	13, // 3: mumaxpy.MumaxObjects.s:type_name -> mumaxpy.MumaxObject
	13, // 4: mumaxpy.FunctionCall.argMumax:type_name -> mumaxpy.MumaxObject
	26, // 5: mumaxpy.FunctionCall.argScalarFunction:type_name -> mumaxpy.ScalarFunction
	29, // 6: mumaxpy.FunctionCall.argVectorFunction:type_name -> mumaxpy.VectorFunction
	6,  // 7: mumaxpy.Array.i:type_name -> mumaxpy.INTs
	4,  // 8: mumaxpy.Array.b:type_name -> mumaxpy.BOOLs
	2,  // 9: mumaxpy.Array.s:type_name -> mumaxpy.STRINGs
	8,  // 10: mumaxpy.Array.d:type_name -> mumaxpy.DOUBLEs
	14, // 11: mumaxpy.Array.o:type_name -> mumaxpy.MumaxObjects
	17, // 12: mumaxpy.Array.a:type_name -> mumaxpy.Arrays
	16, // 13: mumaxpy.Arrays.s:type_name -> mumaxpy.Array
	13, // 14: mumaxpy.CallResponse.outMumax:type_name -> mumaxpy.MumaxObject
	16, // 15: mumaxpy.CallResponse.outArray:type_name -> mumaxpy.Array
	13, // 16: mumaxpy.MethodCall.mmobj:type_name -> mumaxpy.MumaxObject
	15, // 17: mumaxpy.MethodCall.fc:type_name -> mumaxpy.FunctionCall
	13, // 18: mumaxpy.MumaxField.mmobj:type_name -> mumaxpy.MumaxObject
	13, // 19: mumaxpy.BoolSet.mmobj:type_name -> mumaxpy.MumaxObject
	13, // 20: mumaxpy.IntSet.mmobj:type_name -> mumaxpy.MumaxObject
	13, // 21: mumaxpy.DoubleSet.mmobj:type_name -> mumaxpy.MumaxObject
	13, // 22: mumaxpy.StringSet.mmobj:type_name -> mumaxpy.MumaxObject
	13, // 23: mumaxpy.VectorSet.mmobj:type_name -> mumaxpy.MumaxObject
	13, // 24: mumaxpy.ScalarFunctionSet.mmobj:type_name -> mumaxpy.MumaxObject
	26, // 25: mumaxpy.ScalarFunctionSet.s:type_name -> mumaxpy.ScalarFunction
	26, // 26: mumaxpy.ScalarFunction3.x:type_name -> mumaxpy.ScalarFunction
	26, // 27: mumaxpy.ScalarFunction3.y:type_name -> mumaxpy.ScalarFunction
	26, // 28: mumaxpy.ScalarFunction3.z:type_name -> mumaxpy.ScalarFunction
	28, // 29: mumaxpy.VectorFunction.components:type_name -> mumaxpy.ScalarFunction3
	13, // 30: mumaxpy.VectorFunctionSet.mmobj:type_name -> mumaxpy.MumaxObject
	29, // 31: mumaxpy.VectorFunctionSet.s:type_name -> mumaxpy.VectorFunction
	13, // 32: mumaxpy.MumaxSet.mmobj:type_name -> mumaxpy.MumaxObject
	13, // 33: mumaxpy.MumaxSet.s:type_name -> mumaxpy.MumaxObject
	1,  // 34: mumaxpy.mumax.Eval:input_type -> mumaxpy.STRING
	0,  // 35: mumaxpy.mumax.GetIdentifiers:input_type -> mumaxpy.NULL
	1,  // 36: mumaxpy.mumax.GetTypeInfo:input_type -> mumaxpy.STRING
	15, // 37: mumaxpy.mumax.Call:input_type -> mumaxpy.FunctionCall
	19, // 38: mumaxpy.mumax.CallMethod:input_type -> mumaxpy.MethodCall
	13, // 39: mumaxpy.mumax.GetBool:input_type -> mumaxpy.MumaxObject
	13, // 40: mumaxpy.mumax.GetInt:input_type -> mumaxpy.MumaxObject
	13, // 41: mumaxpy.mumax.GetString:input_type -> mumaxpy.MumaxObject
	13, // 42: mumaxpy.mumax.GetDouble:input_type -> mumaxpy.MumaxObject
	21, // 43: mumaxpy.mumax.SetBool:input_type -> mumaxpy.BoolSet
	22, // 44: mumaxpy.mumax.SetInt:input_type -> mumaxpy.IntSet
	23, // 45: mumaxpy.mumax.SetDouble:input_type -> mumaxpy.DoubleSet
	24, // 46: mumaxpy.mumax.SetString:input_type -> mumaxpy.StringSet
	25, // 47: mumaxpy.mumax.SetVector:input_type -> mumaxpy.VectorSet
	27, // 48: mumaxpy.mumax.SetScalarFunction:input_type -> mumaxpy.ScalarFunctionSet
	30, // 49: mumaxpy.mumax.SetVectorFunction:input_type -> mumaxpy.VectorFunctionSet
	31, // 50: mumaxpy.mumax.SetMumax:input_type -> mumaxpy.MumaxSet
	20, // 51: mumaxpy.mumax.GetFieldBool:input_type -> mumaxpy.MumaxField
	20, // 52: mumaxpy.mumax.GetFieldInt:input_type -> mumaxpy.MumaxField
	20, // 53: mumaxpy.mumax.GetFieldString:input_type -> mumaxpy.MumaxField
	20, // 54: mumaxpy.mumax.GetFieldDouble:input_type -> mumaxpy.MumaxField
	20, // 55: mumaxpy.mumax.GetFieldMumax:input_type -> mumaxpy.MumaxField
	13, // 56: mumaxpy.mumax.DestroyMumax:input_type -> mumaxpy.MumaxObject
	32, // 57: mumaxpy.mumax.NewSlice:input_type -> mumaxpy.Slice
	0,  // 58: mumaxpy.mumax.Eval:output_type -> mumaxpy.NULL
	12, // 59: mumaxpy.mumax.GetIdentifiers:output_type -> mumaxpy.Identifier
	12, // 60: mumaxpy.mumax.GetTypeInfo:output_type -> mumaxpy.Identifier
	18, // 61: mumaxpy.mumax.Call:output_type -> mumaxpy.CallResponse
	18, // 62: mumaxpy.mumax.CallMethod:output_type -> mumaxpy.CallResponse
	3,  // 63: mumaxpy.mumax.GetBool:output_type -> mumaxpy.BOOL
	5,  // 64: mumaxpy.mumax.GetInt:output_type -> mumaxpy.INT
	1,  // 65: mumaxpy.mumax.GetString:output_type -> mumaxpy.STRING
	7,  // 66: mumaxpy.mumax.GetDouble:output_type -> mumaxpy.DOUBLE
	0,  // 67: mumaxpy.mumax.SetBool:output_type -> mumaxpy.NULL
	0,  // 68: mumaxpy.mumax.SetInt:output_type -> mumaxpy.NULL
	0,  // 69: mumaxpy.mumax.SetDouble:output_type -> mumaxpy.NULL
	0,  // 70: mumaxpy.mumax.SetString:output_type -> mumaxpy.NULL
	0,  // 71: mumaxpy.mumax.SetVector:output_type -> mumaxpy.NULL
	0,  // 72: mumaxpy.mumax.SetScalarFunction:output_type -> mumaxpy.NULL
	0,  // 73: mumaxpy.mumax.SetVectorFunction:output_type -> mumaxpy.NULL
	0,  // 74: mumaxpy.mumax.SetMumax:output_type -> mumaxpy.NULL
	3,  // 75: mumaxpy.mumax.GetFieldBool:output_type -> mumaxpy.BOOL
	5,  // 76: mumaxpy.mumax.GetFieldInt:output_type -> mumaxpy.INT
	1,  // 77: mumaxpy.mumax.GetFieldString:output_type -> mumaxpy.STRING
	7,  // 78: mumaxpy.mumax.GetFieldDouble:output_type -> mumaxpy.DOUBLE
	13, // 79: mumaxpy.mumax.GetFieldMumax:output_type -> mumaxpy.MumaxObject
	0,  // 80: mumaxpy.mumax.DestroyMumax:output_type -> mumaxpy.NULL
	13, // 81: mumaxpy.mumax.NewSlice:output_type -> mumaxpy.MumaxObject
	58, // [58:82] is the sub-list for method output_type
	34, // [34:58] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_mumax_proto_init() }
func file_mumax_proto_init() {
	if File_mumax_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mumax_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NULL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*STRING); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*STRINGs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BOOL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BOOLs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INTs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DOUBLE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DOUBLEs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ROnly); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MumaxObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MumaxObjects); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Arrays); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MumaxField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScalarFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScalarFunctionSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScalarFunction3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VectorFunctionSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MumaxSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mumax_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_mumax_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*Identifier_L)(nil),
		(*Identifier_R)(nil),
		(*Identifier_F)(nil),
	}
	file_mumax_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*MumaxObject_Name)(nil),
		(*MumaxObject_Ptr)(nil),
	}
	file_mumax_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*Array_I)(nil),
		(*Array_B)(nil),
		(*Array_S)(nil),
		(*Array_D)(nil),
		(*Array_O)(nil),
		(*Array_A)(nil),
	}
	file_mumax_proto_msgTypes[26].OneofWrappers = []interface{}{
		(*ScalarFunction_Scalar)(nil),
		(*ScalarFunction_Gocode)(nil),
	}
	file_mumax_proto_msgTypes[29].OneofWrappers = []interface{}{
		(*VectorFunction_Gocode)(nil),
		(*VectorFunction_Components)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mumax_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mumax_proto_goTypes,
		DependencyIndexes: file_mumax_proto_depIdxs,
		MessageInfos:      file_mumax_proto_msgTypes,
	}.Build()
	File_mumax_proto = out.File
	file_mumax_proto_rawDesc = nil
	file_mumax_proto_goTypes = nil
	file_mumax_proto_depIdxs = nil
}
